const apiRoute = require("express").Router();
const authRoute = require("./auth.route");
const hotelRoute = require("./hotel.route");
const meRoute = require("./me.route");
const roomRoute = require("./room.route");
const ratingRoute = require("./rating.route");
apiRoute.use("/auth", authRoute);
apiRoute.use("/hotel", hotelRoute);
apiRoute.use("/me", meRoute);
apiRoute.use("/room", roomRoute);
apiRoute.use("/rating", ratingRoute);
module.exports = apiRoute;
